##
# @File: ConnectTopics.srv
#
# @brief
# Tells the topic server to relay topic messages
##

## The topic the messages are coming from
string topic_in

## The topic the messages are to be published on
string topic_out

## The rate that the topics will updated.
## Default is 30 Hz
uint32 spin_rate

## The lenght of both the publishing and subscribing queues
## Default is 5
uint32 queue_length

---

