##
# @File: ConnectPostionServer.srv
#
# @brief
# Tells the position server to start publishing on the given topic and with the given
# frame ID.
##

## Receivers ROS topic
string topic

## Receivers frame id
string frameId

## Whether or not you want only bots in the neighborhood set
bool filter

---

