##
# @File: DisconnectRebroadcast.srv
#
# @brief
# Tells a rebroadcasting server to stop publishing on the given topic
# @Note: The topic rebroadcaster needs both the topic_out and topic_in,
#        however the position rebroadcaster only needs the topic_out information.
##

## Receivers ROS topic
string topic_out

string topic_in

---

