##
# @File: DisconnectRebroadcast.srv
#
# @brief
# Tells the rebroadcasting server to stop publishing on the given topic
##

## Receivers ROS topic
string topic

---

## Returns true if all went well and false otherwise

bool exitStatus 

