##
# @File: ConnectPostionServer.srv
#
# @brief
# Tells the position server to start publishing on the given topic and with the given
# frame ID.
##

## Receivers ROS topic
string topic

## Receivers frame id
string frameId

---

## Returns true if all went well and false otherwise

bool exitStatus 

